CREATE DATABASE IF NOT EXISTS `traveldb`;
USE traveldb;
CREATE TABLE IF NOT EXISTS travel_items (
    id INT AUTO_INCREMENT,
    name VARCHAR(255),
    weight INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
